CREATE TABLE license_keys
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license  VARCHAR(255) NOT NULL UNIQUE,
    active       BOOLEAN      NOT NULL,
    is_activated BOOLEAN      NOT NULL,
    expire_date  DATE         NOT NULL
);